# Generated by Django 3.2.4 on 2021-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_recipies_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='cooking_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='files/<django.db.models.fields.AutoField>'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='recipie_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='recipie_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
