# Generated by Django 3.2.4 on 2021-09-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUser',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipies',
            fields=[
                ('recipie_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('recipie_name', models.CharField(max_length=100)),
                ('recipie_type', models.CharField(max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('recipie_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_app.websiteuser')),
            ],
        ),
    ]
