# Generated by Django 3.2.4 on 2021-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_auto_20210913_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='cooking_time',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
